name: CHECKING SERVER STATUS
on:
  push:
    branches:
      - jagannath

concurrency:
  group: jagannath
  cancel-in-progress: true

jobs:
  cicd:
    name: Continuous Integration
    uses: .github/workflows/master.yml

  mail-service:
    name: mail_sending
    needs: cicd
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USER: ${{ secrets.SSH_USER }}
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
            chmod 600 ~/.ssh/github
            cat >> ~/.ssh/config <<END
            Host target
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/github
              LogLevel ERROR
              StrictHostKeyChecking no
            END
      - name: Checking server Status
        run: |
          ps aux | grep 'python manage.py runserver 0.0.0.0:2914' | grep -v grep
        id: check_server_status
      - name: Print server status
          run:
            echo "Server status: ${{ steps  .check_server_status.outputs }}"


