###name : Continuous Integration
###
###on:
###  push:
###    branches:
###      - jagannath
###
###concurrency:
###  group: jagannath
###  cancel-in-progress: true
###
###jobs:
###  name: Deploy
###  runs-on: ubuntu-latest
###  steps:
###    -name: Configure SSH
###    env:
###      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
###      SSH_HOST: ${{ secrets.SSH_HOST }}
###      SSH_USER: ${{ secrets.SSH_USER }}
###    run:
###       mkdir -p !/.ssh/
###       echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
###       chmod 600 ~/.ssh/github
###       cat >>~/.ssh/config <<END
###       Host target
###         HostName $SSH_HOST
###         User $SSH_USER
###         IdentityFile ~/.ssh/github
###         LogLevel ERROR
###         StrictHostKeyChecking no
###       END
###    - name: Run deploy
###      run:
###        ssh target "cd cicd_project/cicd/ && docker-compose down && git pull && git pull && docker-compose build && docker-compose up -d --force-recreate"
##name: Continuous Integration
##
##on:
##  push:
##    branches:
##      - jagannath
##
##concurrency:
##  group: jagannath
##  cancel-in-progress: true
##
##jobs:
##  deploy:
##    runs-on: ubuntu-latest
##    steps:
##      - name: Configure SSH
##        env:
##          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
##          SSH_HOST: ${{ secrets.SSH_HOST }}
##          SSH_USER: ${{ secrets.SSH_USER }}
##        run: |
##          mkdir -p ~/.ssh/
##          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
##          chmod 600 ~/.ssh/github
##          cat >> ~/.ssh/config <<END
##          Host target
##            HostName $SSH_HOST
##            User $SSH_USER
##            IdentityFile ~/.ssh/github
##            LogLevel ERROR
##            StrictHostKeyChecking no
##          END
##      - name: Run deploy
##        run: |
###          ssh target "cd cicd_project/cicd/ && docker-compose down && git pull && docker-compose build && docker-compose up -d --force-recreate"
##           ssh target "cd cicd_project/cicd/ && git pull && sudo systemctl restart your-service"
#name: Continuous Integration
#
#on:
#  push:
#    branches:
#      - jagannath
#
#concurrency:
#  group: jagannath
#  cancel-in-progress: true
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Configure SSH
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
#          chmod 600 ~/.ssh/github
#          cat >> ~/.ssh/config <<END
#          Host target
#            HostName $SSH_HOST
#            User $SSH_USER
#            IdentityFile ~/.ssh/github
#            LogLevel ERROR
#            StrictHostKeyChecking no
#          END
#      - name: Run deploy
#        run: |
#          ssh target "cd cicd_project/cicd/ && git pull && sudo systemctl restart your-service"
name: Continuous Integration

on:
  push:
    branches:
      - jagannath

concurrency:
  group: jagannath
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >> ~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Run deploy
        run: |
          sudo chown -R $SSH_USER:$SSH_USER /home/ubuntu/cicd_project/cicd/
          ssh target << 'EOF'
            git config --global --add safe.directory /home/ubuntu/cicd_project/cicd/
            cd /home/ubuntu/cicd_project/cicd/
            git pull
            source /home/ubuntu/cicd_project/cicd_env/bin/activate
            sudo systemctl /home/ubuntu/cicd_project/cicd_env/bin/python manage.py runserver 0.0.0.0:2914
          EOF
