###name: Continuous Integration
###
###on:
###  push:
###    branches:
###      - jagannath
###
###concurrency:
###  group: jagannath
###  cancel-in-progress: true
###
###jobs:
###  deploy:
###    runs-on: ubuntu-latest
###    steps:
###      - name: Configure SSH
###        env:
###          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
###          SSH_HOST: ${{ secrets.SSH_HOST }}
###          SSH_USER: ${{ secrets.SSH_USER }}
###        run: |
###          mkdir -p ~/.ssh/
###          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
###          chmod 600 ~/.ssh/github
###          cat >> ~/.ssh/config <<END
###          Host target
###            HostName $SSH_HOST
###            User $SSH_USER
###            IdentityFile ~/.ssh/github
###            LogLevel ERROR
###            StrictHostKeyChecking no
###          END
###      - name: Run deploy
###        run: |
###          ssh target << 'EOF'
###            sudo chmod -R 777 /home/ubuntu/cicd_project/cicd
###            git config --global --add safe.directory /home/ubuntu/cicd_project/cicd
###            source /home/ubuntu/cicd_project/cicd_env/bin/activate
###            cd /home/ubuntu/cicd_project/cicd
###            git pull
###            python manage.py runserver 0.0.0.0:2914
###          EOF
##
##name: Continuous Integration
##
##on:
##  push:
##    branches:
##      - jagannath
##
##concurrency:
##  group: jagannath
##  cancel-in-progress: true
##
##jobs:
##  deploy:
##    runs-on: ubuntu-latest
##    steps:
##      - name: Configure SSH
##        env:
##          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
##          SSH_HOST: ${{ secrets.SSH_HOST }}
##          SSH_USER: ${{ secrets.SSH_USER }}
##        run: |
##          mkdir -p ~/.ssh/
##          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
##          chmod 600 ~/.ssh/github
##          cat >> ~/.ssh/config <<END
##          Host target
##            HostName $SSH_HOST
##            User $SSH_USER
##            IdentityFile ~/.ssh/github
##            LogLevel ERROR
##            StrictHostKeyChecking no
##          END
##      - name: Checking Screen
##        run: |
##          ssh target "sudo screen -list"
##      - name: Run deploy
##        run: |
##          ssh target << 'EOF'
##            # Check if the screen session exists
##            if sudo screen -list | grep -q 150841; then
##              echo "Screen session found. Proceeding with deployment."
##              # Stop the running server in the screen session
##              sudo screen -S 150841 stuff 'pkill -f python manage.py runserver 0.0.0.0:2914'
##              sleep 5  # Wait for the server to stop
##              # Start the server again in the screen session
##              sudo screen -S 150841 -X stuff source /home/ubuntu/cicd_project/cicd_env/bin/activate
##              echo "env activated."
##              # Change to the project directory and pull the latest changes
##              sudo chmod -R 777 /home/ubuntu/cicd_project/cicd_pro/cicd
##              git config --global --add safe.directory /home/ubuntu/cicd_project/cicd_pro/cicd
##              cd /home/ubuntu/cicd_project/cicd_pro/cicd/
##              git pull
##              sudo screen -S 150841 -X stuff python manage.py runserver 0.0.0.0:2914
##              echo "deployed."
##            else
##              echo "No screen session found. Aborting. Hi jagannath"
##              exit 1
##            fi
##          EOF
#
#
##name: Continuous Integration
##
##on:
##  push:
##    branches:
##      - jagannath
##
##concurrency:
##  group: jagannath
##  cancel-in-progress: true
##
##jobs:
##  deploy:
##    runs-on: ubuntu-latest
##    steps:
##      - name: Configure SSH
##        env:
##          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
##          SSH_HOST: ${{ secrets.SSH_HOST }}
##          SSH_USER: ${{ secrets.SSH_USER }}
##        run: |
##          mkdir -p ~/.ssh/
##          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
##          chmod 600 ~/.ssh/github
##          cat >> ~/.ssh/config <<END
##          Host target
##            HostName $SSH_HOST
##            User $SSH_USER
##            IdentityFile ~/.ssh/github
##            LogLevel ERROR
##            StrictHostKeyChecking no
##          END
##      - name: Checking Screen
##        run: |
##          ssh target "sudo screen -list"
##      - name: Run deploy
##        run: |
##          ssh target << 'EOF'
##            # Check if the screen session exists
##            if sudo screen -list | grep -q 150841; then
##              echo "Screen session found. Proceeding with deployment."
##              #################################################################
##              # Stop the running server in the screen session
##              sudo screen -S 150841 -X stuff 'pkill -f python manage.py runserver 0.0.0.0:2914'
##              sleep 5  # Wait for the server to stop
##              #################################################################
##              # Start the server again in the screen session
##              sudo screen -S 150841 -X stuff source /home/ubuntu/cicd_project/cicd_env/bin/activate
##              echo "env activated."
##              ##################################################################
##              # Change to the project directory and pull the latest changes
##              git config --global --add safe.directory /home/ubuntu/cicd_project/cicd
##              sudo chmod -R 777 /home/ubuntu/cicd_project/cicd
##              cd /home/ubuntu/cicd_project/cicd/
##              git pull
##              sudo screen -S 150841 -X stuff python manage.py runserver 0.0.0.0:2914
##              echo "deployed."
##            else
##              echo "No screen session found. Aborting. Hi jagannath"
##              exit 1
##            fi
##          EOF
#
#
#name: Continuous Integration
#
#on:
#  push:
#    branches:
#      - jagannath
#
#concurrency:
#  group: jagannath
#  cancel-in-progress: true
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Configure SSH
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
#          chmod 600 ~/.ssh/github
#          cat >> ~/.ssh/config <<END
#          Host target
#            HostName $SSH_HOST
#            User $SSH_USER
#            IdentityFile ~/.ssh/github
#            LogLevel ERROR
#            StrictHostKeyChecking no
#          END
#      - name: Checking Screen
#        run: |
#          ssh target "sudo screen -list"
#      - name: Run deploy
#        run: |
#          ssh target << 'EOF'
#            # Check if the screen session exists
#            if sudo screen -list | grep -q 150841; then
#              echo "Screen session found. Proceeding with deployment."
#              #################################################################
#              # Stop the running server in the screen session
#              sudo screen -S 150841 -X stuff 'pkill -f python manage.py runserver 0.0.0.0:2914\n'
#              sleep 5  # Wait for the server to stop
#              #################################################################
#              # Discard local changes and untracked files
#              cd /home/ubuntu/cicd_project/cicd/
#              git reset --hard HEAD
#              git clean -fd
#              ##################################################################
#              # Pull the latest changes
#              git config --global --add safe.directory /home/ubuntu/cicd_project/cicd
#              sudo chmod -R 777 /home/ubuntu/cicd_project/cicd
#              git pull
#              ##################################################################
#              # Start the server again in the screen session
#              sudo screen -S 150841 -X stuff 'source /home/ubuntu/cicd_project/cicd_env/bin/activate\n'
#              echo "env activated."
#              sudo screen -S 150841 -X stuff 'python manage.py runserver 0.0.0.0:2914\n'
#              echo "deployed."
#            else
#              echo "No screen session found. Aborting. Hi jagannath"
#              exit 1
#            fi
#          EOF


#################################################################
#name: Continuous Integration
#
#on:
#  push:
#    branches:
#      - jagannath
#
#concurrency:
#  group: jagannath
#  cancel-in-progress: true
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Configure SSH
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
#          chmod 600 ~/.ssh/github
#          cat >> ~/.ssh/config <<END
#          Host target
#            HostName $SSH_HOST
#            User $SSH_USER
#            IdentityFile ~/.ssh/github
#            LogLevel ERROR
#            StrictHostKeyChecking no
#          END
#      - name: Checking Screen
#        run: |
#          ssh target "sudo screen -list"
#      - name: Run deploy
#        run: |
#          ssh target << 'EOF'
#          sudo pkill -f 'python manage.py runserver 0.0.0.0:2914'
#          echo "service stopped"
#          sleep 5  # Wait for the server to stop
#          #################################################################
#            # Check if the screen session exists
#            if sudo screen -list | grep -q 150841; then
#              echo "Screen session found. Proceeding with deployment."
#              ##################################################################
#              # Force pull the latest changes
#              sudo screen -S 150841 -X stuff 'cd /home/ubuntu/cicd_project/cicd\n'
#              #cd /home/ubuntu/cicd_project/cicd\n
#              sudo screen -S 150841 -X stuff 'git pull\n'
#              #git fetch origin
#              #git reset --hard origin/jagannath
#              ##################################################################
#              # Start the server again in the screen session
#              sudo screen -S 150841 -X stuff 'source /home/ubuntu/cicd_project/cicd_env/bin/activate\n'
#              echo "env activated."
#              sudo screen -S 150841 -X stuff 'pip install -r requirements.txt\n'
#              echo "Installing requirements"
#              sleep 5
#              sudo screen -S 150841 -X stuff 'python manage.py runserver 0.0.0.0:2914\n'
#              echo "deployed."
#            else
#              echo "No screen session found. Aborting. Hi jagannath"
#              exit 1
#            fi
#          EOF
#############################################################################
name: Continuous Integration

on:
  push:
    branches:
      - jagannath

concurrency:
  group: jagannath
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >> ~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      - name: Checking Screen
        run: |
          ssh target "sudo screen -list"
      - name: Run deploy
        run: |
          ssh target << 'EOF'
          sudo pkill -f 'python manage.py runserver 0.0.0.0:2914'
          echo "service stopped"
          sleep 5  # Wait for the server to stop
          #################################################################
          # Check if the screen session exists
          if sudo screen -list | grep -q 150841; then
            echo "Screen session found. Proceeding with deployment."
            ##################################################################
            # Force pull the latest changes
            sudo screen -S 150841 -X stuff 'cd /home/ubuntu/cicd_project/cicd\n'
            sudo screen -S 150841 -X stuff 'git pull\n'
            ##################################################################
            # Start the server again in the screen session
            sudo screen -S 150841 -X stuff 'source /home/ubuntu/cicd_project/cicd_env/bin/activate\n'
            echo "env activated."
            sudo screen -S 150841 -X stuff 'pip install -r requirements.txt\n'
            echo "Installing requirements"
            sleep 5
            sudo screen -S 150841 -X stuff 'python manage.py runserver 0.0.0.0:2914\n'
            echo "deployed."
          else
            echo "No screen session found. Aborting. Hi jagannath"
            exit 1
          fi
          EOF

      - name: Wait for server to start
        run: |
          ssh target << 'EOF'
          for i in {1..10}; do
            if ps aux | grep 'python manage.py runserver 0.0.0.0:2914' | grep -v grep; then
              echo "Server is running."
              exit 0
            fi
            echo "Waiting for the server to start..."
            sleep 3
          done
          echo "Server did not start in time."
          exit 1
          EOF

      - name: Run Python file if deployment failed
        if: failure()
        run: python mail.py
